apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kruise
  namespace: vela-system
spec:
  workflow:
    steps:
      - name: checking-depends-on
        type: depends-on-app
        properties:
          name: fluxcd
          namespace: vela-system
      - name: apply-resources
        type: apply-application
  components:
    - name: kruise
      type: helm
      properties:
        repoType: git
        url: https://github.com/openkruise/kruise
        chart: ./charts/kruise/v0.9.0
        git:
          branch: master
        values:
          featureGates: PreDownloadImageForInPlaceUpdate=true

