apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: observability
  namespace: vela-system
spec:
  workflow:
    steps:
      - name: checking-depends-on
        type: depends-on-app
        properties:
          name: fluxcd
          namespace: vela-system
      - name: apply-resources
        type: apply-remaining
  components: []