name: Cloud

on:
  schedule:
    # Run test on Every Friday
    - cron: "0 0 * * FRI"
  workflow_dispatch: {}


jobs:
  aliyun-regular-check:
    env:
      GO_VERSION: 1.17
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup Ginkgo
        run: |
          go install github.com/onsi/ginkgo@v1.16.5
          ginkgo version
      - uses: actions/checkout@v2
      - name: Setup VelaD and vela-core
        run: |
          curl -fsSl https://static.kubevela.net/script/install-velad.sh | sudo bash
          sudo velad version
          sudo velad install
          vela version

      - name: Install addons of terraform and providers
        run: |
          vela addon enable terraform
          vela addon enable terraform-alibaba
          vela addon list
      - name: Configure provider
        run: vela provider add terraform-alibaba --ALICLOUD_ACCESS_KEY=${{ secrets.ALICLOUD_ACCESS_KEY }} --ALICLOUD_SECRET_KEY=${{ secrets.ALICLOUD_SECRET_KEY }} --ALICLOUD_REGION=${{ secrets.ALICLOUD_REGION }}
      - name: run regular check
        run: |
          export KUBECONFIG=$(velad kubeconfig --host) 
          ginkgo run ./test/e2e-test/terraform-test
        
